contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #bpop channel"
    url: https://nfcore.slack.com/channels/bpop
    about: Discussion about the nf-core/bpop pipeline
